openapi: "3.0.1"
info:
  title: AnyResponseCodeDemo
  version: "1.0"
paths:
  /:
    get:
      parameters:
      - name: expect_code
        in: query
        schema:
          type: string
      responses:
        200:
          description: 200 response
          headers:
            X-Any-Response-Code:
              schema:
                type: string
          content: {}
        400:
          description: 400 response
          content: {}
        401:
          description: 401 response
          content: {}
        403:
          description: 403 response
          content: {}
        500:
          description: 500 response
          content: {}
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AnyResponseCodeDemoFunction.Arn}/invocations
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.X-Any-Response-Code: "'*'"
          Bad Request:
            statusCode: "400"
            responseTemplates:
              application/json: |
                {
                  "message": "$input.path('errorMessage')"
                }
          Unauthorixed:
            statusCode: "401"
            responseTemplates:
              application/json: |
                {
                  "message": "$input.path('errorMessage')"
                }
          あなたにはアクセス権がありません:
            statusCode: "403"
            responseTemplates:
              application/json: |
                {
                  "message": "$input.path('errorMessage')"
                }
          Internal Server Error:
            statusCode: "500"
            responseTemplates:
              application/json: |
                {
                  "message": "$input.path('errorMessage')"
                }
        passthroughBehavior: WHEN_NO_TEMPLATES
        httpMethod: POST
        requestTemplates:
          application/json: |
            #set($allParams = $input.params())
            {
              "queryStringParameters" : {
                #set($params = $allParams.get('querystring'))
                #foreach($paramName in $params.keySet())
                "$paramName" : "$util.escapeJavaScript($params.get($paramName))"
                  #if($foreach.hasNext),#end
                #end
              }
            }
        type: aws
    options:
      responses:
        200:
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 200
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        requestTemplates:
          application/json: |
            { "statusCode": 200 }
        passthroughBehavior: WHEN_NO_MATCH
        type: mock
