AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3

Resources:
  AnyResponseCodeDemoApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: swagger.yaml

  AnyResponseCodeDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: app.lambda_handler
      Runtime: python2.7
      Events:
        AnyResponseCodeDemo:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref AnyResponseCodeDemoApi
